# nixpacks.toml

# Ya no necesitamos una fase de build explícita si solo contenía collectstatic.
# Nixpacks suele hacer collectstatic automáticamente si Django es detectado.
# Si tus estáticos no funcionan, podemos añadirlo de vuelta, pero por ahora simplifiquemos.
# Si necesitas collectstatic, se podría añadir aquí:
# [phases.build]
# commands = ["python manage.py collectstatic --noinput"]


# Elimina la sección [phases.release] para migrate.
# [phases.release]
# commands = ["python manage.py migrate --noinput"]


# ¡La magia ocurre aquí!
# Ejecutamos migrate y luego iniciamos Gunicorn, todo en la misma línea (o con &&).
[start]
cmd = "/opt/venv/bin/python manage.py migrate --noinput && /opt/venv/bin/gunicorn project_anfa.wsgi:application --bind 0.0.0.0:$PORT"