# nixpacks.toml

[phases.setup]
commands = [
  "python manage.py makemigrations --noinput",
  "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn project_anfa.wsgi:application --bind 0.0.0.0:$PORT"