# nixpacks.toml

# Deja que Nixpacks maneje la instalación de requirements.txt automáticamente.
# No necesitamos especificar [phases.install] ni repetir pip install en [phases.build].
# Nixpacks lo hace por defecto para proyectos Python.

[phases.build]
# Si necesitas collectstatic, este es un buen lugar.
# Se ejecuta después de que las dependencias (incluyendo Django) ya han sido instaladas
# por la lógica interna de Nixpacks.
commands = [
  "python manage.py collectstatic --noinput"
]

[phases.release]
# El comando migrate debe ir aquí.
# Esta fase se ejecuta DESPUÉS de la fase 'build' y la instalación de dependencias,
# y ANTES de que la aplicación empiece a servir tráfico.
commands = [
  "python manage.py migrate --noinput"
]

[start]
cmd = "/opt/venv/bin/gunicorn project_anfa.wsgi:application --bind 0.0.0.0:$PORT"