# nixpacks.toml

[phases.build]
# Forzamos la instalación de dependencias aquí, aunque Nixpacks lo haga por defecto.
# Esto asegura que la capa Docker para la instalación se cree antes de cualquier comando de Django.
commands = [
  "python -m venv --copies /opt/venv", # Crear el entorno virtual si no está
  ". /opt/venv/bin/activate",         # Activar el entorno virtual
  "pip install -r requirements.txt",  # Instalar las dependencias
  "python manage.py collectstatic --noinput" # También un buen lugar para collectstatic
]

[phases.release]
# Ahora, 'migrate' se ejecutará después de que las dependencias se instalaron en la fase 'build'.
commands = [
  "python manage.py migrate --noinput"
]

[start]
cmd = "/opt/venv/bin/gunicorn project_anfa.wsgi:application --bind 0.0.0.0:$PORT"
# IMPORTANTE: Asegúrate de usar el gunicorn del entorno virtual