# nixpacks.toml

# Especifica el comando de inicio para Django con Gunicorn
[start]
cmd = "gunicorn project_anfa.wsgi:application --bind 0.0.0.0:$PORT"

# Puedes añadir otras configuraciones si las necesitas, por ejemplo:
# [phases.setup]
# commands = ["pip install -r requirements.txt"]
# (aunque Nixpacks suele detectar y ejecutar la instalación automáticamente)