# Generated by Django 5.1.6 on 2025-06-27 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=100, unique=True)),
                ('super_seniors', models.BooleanField(default=False)),
                ('seniors', models.BooleanField(default=False)),
                ('honor', models.BooleanField(default=False)),
                ('segunda_honor', models.BooleanField(default=False)),
                ('juveniles', models.BooleanField(default=False)),
                ('primera_infantil', models.BooleanField(default=False)),
                ('segunda_infantil', models.BooleanField(default=False)),
                ('tercera_infantil', models.BooleanField(default=False)),
                ('femenino', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ValorArbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50, unique=True)),
                ('medio_tiempo_min', models.PositiveSmallIntegerField()),
                ('tiempo_completo_min', models.PositiveSmallIntegerField()),
                ('tiempo_con_descanso', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cantidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EncargadoSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidente', models.CharField(max_length=100)),
                ('super_seniors', models.CharField(blank=True, max_length=100, null=True)),
                ('seniors', models.CharField(blank=True, max_length=100, null=True)),
                ('honor', models.CharField(blank=True, max_length=100, null=True)),
                ('segunda_honor', models.CharField(blank=True, max_length=100, null=True)),
                ('juveniles', models.CharField(blank=True, max_length=100, null=True)),
                ('primera_infantil', models.CharField(blank=True, max_length=100, null=True)),
                ('segunda_infantil', models.CharField(blank=True, max_length=100, null=True)),
                ('tercera_infantil', models.CharField(blank=True, max_length=100, null=True)),
                ('femenino', models.CharField(blank=True, max_length=100, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.participante')),
            ],
        ),
    ]
