# Generated by Django 5.1.6 on 2025-07-04 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=100, unique=True)),
                ('super_seniors', models.BooleanField(default=False)),
                ('seniors', models.BooleanField(default=False)),
                ('honor', models.BooleanField(default=False)),
                ('segunda_honor', models.BooleanField(default=False)),
                ('juveniles', models.BooleanField(default=False)),
                ('primera_infantil', models.BooleanField(default=False)),
                ('segunda_infantil', models.BooleanField(default=False)),
                ('tercera_infantil', models.BooleanField(default=False)),
                ('femenino', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValorArbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50, unique=True)),
                ('medio_tiempo_min', models.PositiveSmallIntegerField()),
                ('tiempo_completo_min', models.PositiveSmallIntegerField()),
                ('tiempo_con_descanso', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cantidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EncargadoSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidente', models.CharField(blank=True, default='', max_length=100)),
                ('super_seniors', models.CharField(blank=True, default='', max_length=100)),
                ('seniors', models.CharField(blank=True, default='', max_length=100)),
                ('honor', models.CharField(blank=True, default='', max_length=100)),
                ('segunda_honor', models.CharField(blank=True, default='', max_length=100)),
                ('juveniles', models.CharField(blank=True, default='', max_length=100)),
                ('primera_infantil', models.CharField(blank=True, default='', max_length=100)),
                ('segunda_infantil', models.CharField(blank=True, default='', max_length=100)),
                ('tercera_infantil', models.CharField(blank=True, default='', max_length=100)),
                ('femenino', models.CharField(blank=True, default='', max_length=100)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to='app_main.clubes')),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='app_main.fase')),
            ],
        ),
        migrations.CreateModel(
            name='SerieFemenino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_partido_local', models.CharField(choices=[('PARTIDO GANADO', 'PARTIDO GANADO'), ('PARTIDO EMPATADO', 'PARTIDO EMPATADO'), ('PARTIDO PERDIDO', 'PARTIDO PERDIDO')], max_length=50)),
                ('goles_local', models.PositiveSmallIntegerField()),
                ('goles_visita', models.PositiveSmallIntegerField()),
                ('estado_partido_visita', models.CharField(choices=[('PARTIDO GANADO', 'PARTIDO GANADO'), ('PARTIDO EMPATADO', 'PARTIDO EMPATADO'), ('PARTIDO PERDIDO', 'PARTIDO PERDIDO')], max_length=50)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cancha', models.CharField(blank=True, default='', max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('libre', models.CharField(blank=True, default='', max_length=100)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local_femenino', to='app_main.clubes')),
                ('equipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visita_femenino', to='app_main.clubes')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_femenino', to='app_main.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='SerieHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_partido_local', models.CharField(choices=[('PARTIDO GANADO', 'PARTIDO GANADO'), ('PARTIDO EMPATADO', 'PARTIDO EMPATADO'), ('PARTIDO PERDIDO', 'PARTIDO PERDIDO')], max_length=50)),
                ('goles_local', models.PositiveSmallIntegerField()),
                ('goles_visita', models.PositiveSmallIntegerField()),
                ('estado_partido_visita', models.CharField(choices=[('PARTIDO GANADO', 'PARTIDO GANADO'), ('PARTIDO EMPATADO', 'PARTIDO EMPATADO'), ('PARTIDO PERDIDO', 'PARTIDO PERDIDO')], max_length=50)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cancha', models.CharField(blank=True, default='', max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('libre', models.CharField(blank=True, default='', max_length=100)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='app_main.clubes')),
                ('equipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visita', to='app_main.clubes')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='app_main.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='SerieSegundaAdultos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_partido_local', models.CharField(choices=[('PARTIDO GANADO', 'PARTIDO GANADO'), ('PARTIDO EMPATADO', 'PARTIDO EMPATADO'), ('PARTIDO PERDIDO', 'PARTIDO PERDIDO')], max_length=50)),
                ('goles_local', models.PositiveSmallIntegerField()),
                ('goles_visita', models.PositiveSmallIntegerField()),
                ('estado_partido_visita', models.CharField(choices=[('PARTIDO GANADO', 'PARTIDO GANADO'), ('PARTIDO EMPATADO', 'PARTIDO EMPATADO'), ('PARTIDO PERDIDO', 'PARTIDO PERDIDO')], max_length=50)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cancha', models.CharField(blank=True, default='', max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('libre', models.CharField(blank=True, default='', max_length=100)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local_segunda_adultos', to='app_main.clubes')),
                ('equipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visita_segunda_adultos', to='app_main.clubes')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_segunda_adultos', to='app_main.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Tablero_SerieFemenino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PJ', models.IntegerField(default=0)),
                ('PG', models.IntegerField(default=0)),
                ('PE', models.IntegerField(default=0)),
                ('PP', models.IntegerField(default=0)),
                ('GF', models.IntegerField(default=0)),
                ('GC', models.IntegerField(default=0)),
                ('DG', models.IntegerField(default=0)),
                ('Pts', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.clubes')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros_femenino', to='app_main.fase')),
            ],
            options={
                'ordering': ['-Pts', '-DG', '-GF'],
                'unique_together': {('fase', 'equipo')},
            },
        ),
        migrations.CreateModel(
            name='Tablero_SerieHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PJ', models.IntegerField(default=0)),
                ('PG', models.IntegerField(default=0)),
                ('PE', models.IntegerField(default=0)),
                ('PP', models.IntegerField(default=0)),
                ('GF', models.IntegerField(default=0)),
                ('GC', models.IntegerField(default=0)),
                ('DG', models.IntegerField(default=0)),
                ('Pts', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.clubes')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros', to='app_main.fase')),
            ],
            options={
                'ordering': ['-Pts', '-DG', '-GF'],
                'unique_together': {('fase', 'equipo')},
            },
        ),
        migrations.CreateModel(
            name='Tablero_SerieSegundaAdultos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PJ', models.IntegerField(default=0)),
                ('PG', models.IntegerField(default=0)),
                ('PE', models.IntegerField(default=0)),
                ('PP', models.IntegerField(default=0)),
                ('GF', models.IntegerField(default=0)),
                ('GC', models.IntegerField(default=0)),
                ('DG', models.IntegerField(default=0)),
                ('Pts', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.clubes')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros_segunda_adultos', to='app_main.fase')),
            ],
            options={
                'ordering': ['-Pts', '-DG', '-GF'],
                'unique_together': {('fase', 'equipo')},
            },
        ),
    ]
