# Generated by Django 5.1.6 on 2025-06-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participante',
            new_name='Clubes',
        ),
    ]
