# Generated by Django 5.1.6 on 2025-06-27 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_rename_participante_clubes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargadoserie',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to='app_main.clubes'),
        ),
        migrations.AlterField(
            model_name='encargadoserie',
            name='femenino',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='encargadoserie',
            name='honor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='encargadoserie',
            name='juveniles',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='encargadoserie',
            name='presidente',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='encargadoserie',
            name='primera_infantil',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='encargadoserie',
            name='segunda_honor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='encargadoserie',
            name='segunda_infantil',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='encargadoserie',
            name='seniors',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='encargadoserie',
            name='super_seniors',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='encargadoserie',
            name='tercera_infantil',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
