# Generated by Django 5.1.6 on 2025-07-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_encargadoserie_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_rueda', models.CharField(blank=True, default='', max_length=50)),
                ('jornada', models.CharField(max_length=50)),
                ('estado_partido_local', models.CharField(choices=[('PARTIDO GANADO', 'PARTIDO GANADO'), ('PARTIDO EMPATADO', 'PARTIDO EMPATADO'), ('PARTIDO PERDIDO', 'PARTIDO PERDIDO')], max_length=50)),
                ('goles_local', models.PositiveSmallIntegerField()),
                ('goles_visita', models.PositiveSmallIntegerField()),
                ('estado_partido_visita', models.CharField(choices=[('PARTIDO GANADO', 'PARTIDO GANADO'), ('PARTIDO EMPATADO', 'PARTIDO EMPATADO'), ('PARTIDO PERDIDO', 'PARTIDO PERDIDO')], max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('cancha', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('libre', models.CharField(blank=True, default='', max_length=100)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='app_main.clubes')),
                ('equipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visita', to='app_main.clubes')),
            ],
        ),
    ]
