# Generated by Django 5.1.6 on 2025-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_seriehonor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriehonor',
            name='horario',
            field=models.TimeField(),
        ),
    ]
