# Generated by Django 5.1.6 on 2025-07-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_seriesegundainfantil_tablero_seriesegundainfantil'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieJuvenil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_partido_local', models.CharField(choices=[('PARTIDO GANADO', 'PARTIDO GANADO'), ('PARTIDO EMPATADO', 'PARTIDO EMPATADO'), ('PARTIDO PERDIDO', 'PARTIDO PERDIDO')], max_length=50)),
                ('goles_local', models.PositiveSmallIntegerField()),
                ('goles_visita', models.PositiveSmallIntegerField()),
                ('estado_partido_visita', models.CharField(choices=[('PARTIDO GANADO', 'PARTIDO GANADO'), ('PARTIDO EMPATADO', 'PARTIDO EMPATADO'), ('PARTIDO PERDIDO', 'PARTIDO PERDIDO')], max_length=50)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cancha', models.CharField(blank=True, default='', max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('libre', models.CharField(blank=True, default='', max_length=100)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local_juvenil', to='app_main.clubes')),
                ('equipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visita_juvenil', to='app_main.clubes')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_juvenil', to='app_main.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Tablero_SerieJuvenil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PJ', models.IntegerField(default=0)),
                ('PG', models.IntegerField(default=0)),
                ('PE', models.IntegerField(default=0)),
                ('PP', models.IntegerField(default=0)),
                ('GF', models.IntegerField(default=0)),
                ('GC', models.IntegerField(default=0)),
                ('DG', models.IntegerField(default=0)),
                ('Pts', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.clubes')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros_juvenil', to='app_main.fase')),
            ],
            options={
                'ordering': ['-Pts', '-DG', '-GF'],
                'unique_together': {('fase', 'equipo')},
            },
        ),
    ]
