# Generated by Django 5.1.6 on 2025-07-04 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_seriehonor_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seriehonor',
            name='fase_rueda',
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='app_main.fase')),
            ],
        ),
        migrations.AlterField(
            model_name='seriehonor',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='app_main.jornada'),
        ),
    ]
