# Generated by Django 5.1.6 on 2025-07-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_fase_remove_seriehonor_fase_rueda_jornada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero_SerieHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PJ', models.IntegerField(default=0)),
                ('PG', models.IntegerField(default=0)),
                ('PE', models.IntegerField(default=0)),
                ('PP', models.IntegerField(default=0)),
                ('GF', models.IntegerField(default=0)),
                ('GC', models.IntegerField(default=0)),
                ('DG', models.IntegerField(default=0)),
                ('Pts', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.clubes')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros', to='app_main.fase')),
            ],
            options={
                'ordering': ['-Pts', '-DG', '-GF'],
                'unique_together': {('fase', 'equipo')},
            },
        ),
    ]
