# Generated by Django 5.1.6 on 2025-07-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_serietercerainfantil_tablero_serietercerainfantil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='novedades/')),
                ('url_instagram', models.URLField(blank=True, help_text='URL del post de Instagram relacionado', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
