# Generated by Django 5.1.6 on 2025-07-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_tablero_seriehonor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriehonor',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seriehonor',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
