# Generated by Django 5.1.6 on 2025-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_alter_seriehonor_fecha_alter_seriehonor_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seriehonor',
            name='cancha',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
